--Faixa de selos
CREATE OR REPLACE VIEW LOYALTYCOM.TMP_LOYALTYCOM_SELOS_FAIXA AS

SELECT A.NROEMPRESA,
       A.NROCHECKOUT,
       A.SEQDOCTO,
       A.TIPO,
       A.CODSELO,
       A.ULTCODSELO,
       A.SEQUSUARIO,
       A.QTDESELOSEXCEDENTE,
       A.QTDESELOSROLO,
       C.DTAMOVIMENTO
  FROM MONITORPDV.TB_DOCTOSELOFAIXA@LINK_C5 A INNER JOIN MONITORPDV.TB_DOCTO@LINK_C5 C ON A.NROEMPRESA = C.NROEMPRESA AND A.NROCHECKOUT = C.NROCHECKOUT AND A.SEQDOCTO = C.SEQDOCTO
  
 GROUP BY A.NROEMPRESA,
          A.NROCHECKOUT,
          A.SEQDOCTO,
          A.TIPO,
          A.CODSELO,
          A.ULTCODSELO,
          A.SEQUSUARIO,
          A.QTDESELOSEXCEDENTE,
          A.QTDESELOSROLO,
          C.DTAMOVIMENTO
 ORDER BY 10, 1, 2, 3;
